// =================================================================================================
// Constants
// =================================================================================================
const CALORIES_PER_POUND_OF_FAT = 3500;
const WEEKLY_BODY_WEIGHT_CUT_PERCENTAGE = 0.0075;
const DAILY_BODY_WEIGHT_CUT_PERCENTAGE = WEEKLY_BODY_WEIGHT_CUT_PERCENTAGE / 7;
const WEEKLY_BODY_WEIGHT_BULK_PERCENTAGE = 0.00375;
const DAILY_BODY_WEIGHT_BULK_PERCENTAGE = WEEKLY_BODY_WEIGHT_BULK_PERCENTAGE / 7;

const GRAMS_OF_PROTEIN_PER_POUND_OF_LEAN_MASS = 1.1;
const GRAMS_OF_FAT_PER_POUND_OF_TARGET_WEIGHT = 0.4;
const CALORIES_PER_GRAM_OF_PROTEIN = 4;
const CALORIES_PER_GRAM_OF_FAT = 9;
const CALORIES_PER_GRAM_OF_CARBS = 4;

const MIN_BODY_WEIGHT = 1;
const MAX_BODY_WEIGHT = 10000;
const MIN_RESTING_METABOLIC_RATE = 1;
const MAX_RESTING_METABOLIC_RATE = 100000;
const MIN_LEAN_MASS = 1;
const MAX_LEAN_MASS = 10000;
const MIN_BONE_MASS = 1;
const MAX_BONE_MASS = 10000;
const MIN_TARGET_LEAN_MASS = 1;
const MAX_TARGET_LEAN_MASS = 10000;
const MIN_TARGET_BODY_FAT_PERCENTAGE = 1;
const MAX_TARGET_BODY_FAT_PERCENTAGE = 99;
const MIN_ACTIVITY_LEVEL = 1;
const MAX_ACTIVITY_LEVEL = 3;

const MIN_PERSONAL_RECORD_NAME_LENGTH = 1;
const MAX_PERSONAL_RECORD_NAME_LENGTH = 30;
const MIN_PERSONAL_RECORD_WEIGHT = 0;
const MAX_PERSONAL_RECORD_WEIGHT = 10000;

const MIN_WORKOUT_NAME_LENGTH = 1;
const MAX_WORKOUT_NAME_LENGTH = 30;

const MIN_EXERCISE_NAME_LENGTH = 1;
const MAX_EXERCISE_NAME_LENGTH = 30;
const MIN_EXERCISE_WEIGHT = 0;
const MAX_EXERCISE_WEIGHT = 10000;
const MIN_EXERCISE_SETS = 1;
const MAX_EXERCISE_SETS = 1000;
const MIN_EXERCISE_REPS = 1;
const MAX_EXERCISE_REPS = 1000;

const constants = {
    CALORIES_PER_POUND_OF_FAT,
    WEEKLY_BODY_WEIGHT_CUT_PERCENTAGE,
    DAILY_BODY_WEIGHT_CUT_PERCENTAGE,
    WEEKLY_BODY_WEIGHT_BULK_PERCENTAGE,
    DAILY_BODY_WEIGHT_BULK_PERCENTAGE,

    GRAMS_OF_PROTEIN_PER_POUND_OF_LEAN_MASS,
    GRAMS_OF_FAT_PER_POUND_OF_TARGET_WEIGHT,
    CALORIES_PER_GRAM_OF_PROTEIN,
    CALORIES_PER_GRAM_OF_FAT,
    CALORIES_PER_GRAM_OF_CARBS,

    MIN_BODY_WEIGHT,
    MAX_BODY_WEIGHT,
    MIN_RESTING_METABOLIC_RATE,
    MAX_RESTING_METABOLIC_RATE,
    MIN_LEAN_MASS,
    MAX_LEAN_MASS,
    MIN_BONE_MASS,
    MAX_BONE_MASS,
    MIN_TARGET_LEAN_MASS,
    MAX_TARGET_LEAN_MASS,
    MIN_TARGET_BODY_FAT_PERCENTAGE,
    MAX_TARGET_BODY_FAT_PERCENTAGE,
    MIN_ACTIVITY_LEVEL,
    MAX_ACTIVITY_LEVEL,

    MIN_PERSONAL_RECORD_NAME_LENGTH,
    MAX_PERSONAL_RECORD_NAME_LENGTH,
    MIN_PERSONAL_RECORD_WEIGHT,
    MAX_PERSONAL_RECORD_WEIGHT,

    MIN_WORKOUT_NAME_LENGTH,
    MAX_WORKOUT_NAME_LENGTH,

    MIN_EXERCISE_NAME_LENGTH,
    MAX_EXERCISE_NAME_LENGTH,
    MIN_EXERCISE_WEIGHT,
    MAX_EXERCISE_WEIGHT,
    MIN_EXERCISE_SETS,
    MAX_EXERCISE_SETS,
    MIN_EXERCISE_REPS,
    MAX_EXERCISE_REPS
};

export default constants;
