// API
// Calories
const CALORIES_IN_ONE_POUND_OF_FAT = 3500;
const DAILY_CALORIE_SURPLUS_OR_DEFICIT = CALORIES_IN_ONE_POUND_OF_FAT / 7;

// Macros
const GRAMS_OF_PROTEIN_PER_POUND_OF_LEAN_MASS = 1;
const GRAMS_OF_FAT_PER_POUND_OF_TARGET_WEIGHT = 0.4;
const CALORIES_PER_GRAM_OF_PROTEIN = 4;
const CALORIES_PER_GRAM_OF_FAT = 9;
const CALORIES_PER_GRAM_OF_CARBS = 4;

const constants = {
    CALORIES_IN_ONE_POUND_OF_FAT,
    DAILY_CALORIE_SURPLUS_OR_DEFICIT,

    GRAMS_OF_PROTEIN_PER_POUND_OF_LEAN_MASS,
    GRAMS_OF_FAT_PER_POUND_OF_TARGET_WEIGHT,
    CALORIES_PER_GRAM_OF_PROTEIN,
    CALORIES_PER_GRAM_OF_FAT,
    CALORIES_PER_GRAM_OF_CARBS
};

export default constants;
